services:

  postgres:
    image: postgres:16-alpine
    container_name: biotrack-postgres

    environment:
      POSTGRES_USER: biotrack
      POSTGRES_PASSWORD: biotrack_password
      POSTGRES_DB: biotrack

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: