"""add duration to leave requests

Revision ID: 59838c84e673
Revises: ce7659d89eb3
Create Date: 2026-07-30 14:59:31.877978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "59838c84e673"
down_revision: Union[str, Sequence[str], None] = "ce7659d89eb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "leave_requests",
    sa.Column(
        "duration",
        sa.String(),
        nullable=False,
        server_default="FULL_DAY"
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leave_requests", "duration")
    # ### end Alembic commands ###
