"""create public holidays table

Revision ID: ce6bd361752e
Revises: fa9fdf0d4a31
Create Date: 2026-07-30 11:05:02.135914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6bd361752e'
down_revision: Union[str, Sequence[str], None] = 'fa9fdf0d4a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_holidays',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date')
    )
    op.create_index(op.f('ix_public_holidays_id'), 'public_holidays', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_holidays_id'), table_name='public_holidays')
    op.drop_table('public_holidays')
    # ### end Alembic commands ###
