"""add work schedule table

Revision ID: ce7659d89eb3
Revises: ce6bd361752e
Create Date: 2026-07-30 11:59:40.282963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7659d89eb3'
down_revision: Union[str, Sequence[str], None] = 'ce6bd361752e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_schedule',
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('weekday')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_schedule')
    # ### end Alembic commands ###
